/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minesweeper;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import static java.util.Arrays.sort;
import java.util.Scanner;

/**
 *
 * @author elainewang
 */
public class enterName extends javax.swing.JPanel implements overListener{

    /**
     * Creates new form scores
     */
    String name;
    String[] names = new String[5];
    int[] scores = new int[5];
    Player[] players = new Player[5];
    int newScore;
    
    public enterName() throws FileNotFoundException {
        initComponents();
        File scs = new File("src/minesweeper/scores.txt"); 
        File nms = new File("src/minesweeper/names.txt");
        Scanner sc = new Scanner(scs);
        Scanner nm = new Scanner(nms);
        for(int i = 0; i < names.length; i++){
            names[i] = nm.nextLine();
            scores[i] = sc.nextInt();
            players[i] = new Player(scores[i],names[i]);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        enterButton = new javax.swing.JButton();
        enterNamelbl = new javax.swing.JLabel();
        NameTxtFd = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        enterNamelbl.setText("Enter your name:");

        NameTxtFd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTxtFdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(enterNamelbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameTxtFd, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(enterButton)))))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(enterNamelbl)
                .addGap(85, 85, 85)
                .addComponent(NameTxtFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enterButton)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        // TODO add your handling code here:
        name = NameTxtFd.getText();
        
        int max = scores[4];
        int min = scores[0];
        if (min == 0) {
            players[0].score = (int) newScore;
            players[0].name = name;

        } else if (newScore < max) {
            players[4].score = (int) newScore;
            players[4].name = name;
        }
        
        sort(players);
        
        for(int k = 0; k < 5; k++){
            scores[k] = players[k].score;
            names[k] = players[k].name;
        }
        
       
        try {
            BufferedWriter outs = new BufferedWriter(new FileWriter("/Users/elainewang/Desktop/NetbeansProjects/minesweeper/src/minesweeper/scores.txt"));
            BufferedWriter outn = new BufferedWriter(new FileWriter("/Users/elainewang/Desktop/NetbeansProjects/minesweeper/src/minesweeper/names.txt"));
            for (int score : scores) {
                outs.write(score + "");
                outs.write("\n");
            }
            for (String name : names) {
                outn.write(name + "");
                outn.write("\n");
            }
            outs.close();
            outn.close();
            System.out.println("File created successfully");
            
        } catch (IOException e) {

        }
        
        //disappear enterName panel
        NameTxtFd.setText("");
        this.setVisible(false);
    }//GEN-LAST:event_enterButtonActionPerformed

    private void NameTxtFdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTxtFdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTxtFdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NameTxtFd;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel enterNamelbl;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void gameIsOver(int score) {
        newScore = score;
    }
}
